//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// isEnglishLoanword detects if the expected romanization is English spelling
// rather than Hindi phonetic transliteration
func isEnglishLoanword(hindi, expected string) bool {
	lower := strings.ToLower(expected)

	// Common English words that are loanwords in Hindi
	englishWords := map[string]bool{
		"account": true, "action": true, "active": true, "activity": true,
		"actual": true, "actually": true, "address": true, "administration": true,
		"admission": true, "advance": true, "advertisement": true,
		"africa": true, "afternoon": true, "again": true, "against": true,
		"agent": true, "agreement": true, "air": true, "airport": true,
		"album": true, "alcohol": true, "alert": true, "algorithm": true,
		"all": true, "allow": true, "almost": true, "alone": true,
		"already": true, "also": true, "always": true, "amazing": true,
		"amazon": true, "ambulance": true, "amendment": true, "among": true,
		"amount": true, "analysis": true, "analyst": true, "ancient": true,
		"android": true, "anger": true, "angle": true, "animal": true,
		"anniversary": true, "announce": true, "announcement": true,
		"annual": true, "another": true, "answer": true, "antenna": true,
		"anti": true, "anybody": true, "anyone": true, "anything": true,
		"anyway": true, "anywhere": true, "apartment": true, "app": true,
		"appeal": true, "appear": true, "appearance": true, "apple": true,
		"application": true, "apply": true, "approach": true, "approve": true,
		"architect": true, "architecture": true, "area": true, "arena": true,
		"argue": true, "argument": true, "arm": true, "army": true,
		"around": true, "arrange": true, "arrangement": true, "arrest": true,
		"arrival": true, "arrive": true, "art": true, "article": true,
		"artist": true, "aside": true, "ask": true, "aspect": true,
		"assembly": true, "asset": true, "assignment": true, "assist": true,
		"assistant": true, "associate": true, "association": true, "assume": true,
		"athlete": true, "atmosphere": true, "attach": true, "attack": true,
		"attempt": true, "attend": true, "attention": true, "attitude": true,
		"attorney": true, "attract": true, "attraction": true, "audience": true,
		"audio": true, "august": true, "australia": true, "author": true,
		"auto": true, "automatic": true, "available": true, "average": true,
		"avoid": true, "award": true, "aware": true, "awareness": true,
		"away": true, "awesome": true, "baby": true, "back": true,
		"background": true, "bad": true, "bag": true, "balance": true,
		"ball": true, "ban": true, "band": true, "bank": true,
		"bar": true, "base": true, "baseball": true, "basic": true,
		"basically": true, "basis": true, "basket": true, "basketball": true,
		"batch": true, "battery": true, "battle": true, "beach": true,
		"beat": true, "beautiful": true, "beauty": true, "because": true,
		"become": true, "bed": true, "bedroom": true, "beer": true,
		"before": true, "begin": true, "beginning": true, "behavior": true,
		"behind": true, "being": true, "belief": true, "believe": true,
		"bell": true, "belong": true, "below": true, "belt": true,
		"bench": true, "benefit": true, "besides": true, "best": true,
		"better": true, "between": true, "beyond": true, "big": true,
		"bike": true, "bill": true, "billion": true, "bit": true,
		"black": true, "blame": true, "blank": true, "block": true,
		"blog": true, "blood": true, "blow": true, "blue": true,
		"board": true, "boat": true, "body": true, "bomb": true,
		"bond": true, "bonus": true, "book": true, "boom": true,
		"boot": true, "border": true, "born": true, "borrow": true,
		"boss": true, "both": true, "bother": true, "bottle": true,
		"bottom": true, "box": true, "boy": true, "boyfriend": true,
		"brain": true, "branch": true, "brand": true, "bread": true,
		"break": true, "breakfast": true, "breast": true, "breath": true,
		"bridge": true, "brief": true, "bright": true, "bring": true,
		"broad": true, "broadcast": true, "brother": true, "brown": true,
		"browser": true, "budget": true, "build": true, "building": true,
		"bunch": true, "burden": true, "burn": true, "bus": true,
		"business": true, "busy": true, "but": true, "button": true,
		"buy": true, "buyer": true, "cabinet": true, "cable": true,
		"cake": true, "calculate": true, "calculation": true, "calendar": true,
		"call": true, "camera": true, "camp": true, "campaign": true,
		"campus": true, "can": true, "canada": true, "cancel": true,
		"cancer": true, "candidate": true, "cap": true, "capable": true,
		"capacity": true, "capital": true, "captain": true, "capture": true,
		"car": true, "carbon": true, "card": true, "care": true,
		"career": true, "careful": true, "carefully": true, "carrier": true,
		"carry": true, "case": true, "cash": true, "cast": true,
		"cat": true, "catch": true, "category": true, "cause": true,
		"celebrate": true, "celebration": true, "celebrity": true, "cell": true,
		"center": true, "central": true, "century": true, "ceremony": true,
		"certain": true, "certainly": true, "chain": true, "chair": true,
		"chairman": true, "challenge": true, "chamber": true, "champion": true,
		"championship": true, "chance": true, "change": true, "channel": true,
		"chapter": true, "character": true, "charge": true, "charity": true,
		"chart": true, "chase": true, "chat": true, "cheap": true,
		"check": true, "cheese": true, "chemical": true, "chest": true,
		"chicken": true, "chief": true, "child": true, "children": true,
		"china": true, "chip": true, "chocolate": true, "choice": true,
		"choose": true, "christmas": true, "church": true, "cinema": true,
		"circle": true, "circumstance": true, "citizen": true, "city": true,
		"civil": true, "claim": true, "class": true, "classic": true,
		"classroom": true, "clean": true, "clear": true, "clearly": true,
		"click": true, "client": true, "climate": true, "climb": true,
		"clinic": true, "clock": true, "close": true, "closely": true,
		"clothes": true, "clothing": true, "cloud": true, "club": true,
		"clue": true, "coach": true, "coal": true, "coast": true,
		"coat": true, "code": true, "coffee": true, "coin": true,
		"cold": true, "collapse": true, "colleague": true, "collect": true,
		"collection": true, "college": true, "color": true, "column": true,
		"combination": true, "combine": true, "come": true, "comedy": true,
		"comfort": true, "comfortable": true, "command": true, "comment": true,
		"commercial": true, "commission": true, "commit": true, "commitment": true,
		"committee": true, "common": true, "communicate": true, "communication": true,
		"community": true, "company": true, "compare": true, "comparison": true,
		"compete": true, "competition": true, "competitive": true, "competitor": true,
		"complain": true, "complaint": true, "complete": true, "completely": true,
		"complex": true, "complicated": true, "component": true, "computer": true,
		"concentrate": true, "concentration": true, "concept": true, "concern": true,
		"concert": true, "conclude": true, "conclusion": true, "condition": true,
		"conduct": true, "conference": true, "confidence": true, "confident": true,
		"confirm": true, "conflict": true, "confusion": true, "congress": true,
		"connect": true, "connection": true, "conscious": true, "consequence": true,
		"conservative": true, "consider": true, "consideration": true, "consist": true,
		"consistent": true, "constant": true, "constantly": true, "construction": true,
		"consumer": true, "contact": true, "contain": true, "container": true,
		"content": true, "contest": true, "context": true, "continue": true,
		"contract": true, "contrast": true, "contribute": true, "contribution": true,
		"control": true, "controversial": true, "controversy": true, "conversation": true,
		"convert": true, "convince": true, "cook": true, "cookie": true,
		"cool": true, "cooperation": true, "cop": true, "copy": true,
		"core": true, "corner": true, "corporate": true, "corporation": true,
		"correct": true, "correctly": true, "corruption": true, "cost": true,
		"cotton": true, "couch": true, "could": true, "council": true,
		"count": true, "counter": true, "country": true, "county": true,
		"couple": true, "courage": true, "course": true, "court": true,
		"cousin": true, "cover": true, "coverage": true, "crack": true,
		"craft": true, "crash": true, "crazy": true, "cream": true,
		"create": true, "creation": true, "creative": true, "creature": true,
		"credit": true, "crew": true, "cricket": true, "crime": true,
		"criminal": true, "crisis": true, "criteria": true, "critic": true,
		"critical": true, "criticism": true, "crop": true, "cross": true,
		"crowd": true, "crucial": true, "cry": true, "cultural": true,
		"culture": true, "cup": true, "curious": true, "current": true,
		"currently": true, "curriculum": true, "customer": true, "cut": true,
		"cycle": true, "dad": true, "daily": true, "damage": true,
		"dance": true, "danger": true, "dangerous": true, "dark": true,
		"data": true, "database": true, "date": true, "daughter": true,
		"day": true, "dead": true, "deadline": true, "deal": true,
		"dealer": true, "dear": true, "death": true, "debate": true,
		"debt": true, "decade": true, "decide": true, "decision": true,
		"deck": true, "declare": true, "decline": true, "decrease": true,
		"deep": true, "deeply": true, "defeat": true, "defend": true,
		"defendant": true, "defense": true, "deficit": true, "define": true,
		"definitely": true, "definition": true, "degree": true, "delay": true,
		"deliver": true, "delivery": true, "demand": true, "democracy": true,
		"democratic": true, "demonstrate": true, "demonstration": true, "deny": true,
		"department": true, "depend": true, "dependent": true, "depending": true,
		"deposit": true, "depression": true, "depth": true, "deputy": true,
		"describe": true, "description": true, "desert": true, "deserve": true,
		"design": true, "designer": true, "desire": true, "desk": true,
		"desperate": true, "despite": true, "destroy": true, "destruction": true,
		"detail": true, "detailed": true, "detect": true, "detective": true,
		"determine": true, "develop": true, "developer": true, "development": true,
		"device": true, "dialogue": true, "diamond": true, "dictionary": true,
		"die": true, "diet": true, "differ": true, "difference": true,
		"different": true, "differently": true, "difficult": true, "difficulty": true,
		"dig": true, "digital": true, "dimension": true, "dinner": true,
		"direct": true, "direction": true, "directly": true, "director": true,
		"dirty": true, "disability": true, "disagree": true, "disappear": true,
		"disaster": true, "discipline": true, "discover": true, "discovery": true,
		"discuss": true, "discussion": true, "disease": true, "dish": true,
		"display": true, "dispute": true, "distance": true, "distant": true,
		"distinct": true, "distinction": true, "distribute": true, "distribution": true,
		"district": true, "disturb": true, "dive": true, "diverse": true,
		"diversity": true, "divide": true, "division": true, "divorce": true,
		"dna": true, "doctor": true, "document": true, "documentary": true,
		"dog": true, "dollar": true, "domain": true, "domestic": true,
		"dominant": true, "dominate": true, "donate": true, "donation": true,
		"door": true, "double": true, "doubt": true, "down": true,
		"download": true, "downtown": true, "dozen": true, "draft": true,
		"drag": true, "drama": true, "dramatic": true, "dramatically": true,
		"draw": true, "drawing": true, "dream": true, "dress": true,
		"drink": true, "drive": true, "driver": true, "drop": true,
		"drug": true, "drunk": true, "dry": true, "due": true,
		"during": true, "dust": true, "duty": true, "each": true,
		"ear": true, "early": true, "earn": true, "earnings": true,
		"earth": true, "ease": true, "easily": true, "east": true,
		"eastern": true, "easy": true, "eat": true, "economic": true,
		"economy": true, "edge": true, "edition": true, "editor": true,
		"education": true, "educational": true, "effect": true, "effective": true,
		"effectively": true, "efficiency": true, "efficient": true, "effort": true,
		"egg": true, "eight": true, "either": true, "elderly": true,
		"elect": true, "election": true, "electric": true, "electricity": true,
		"electronic": true, "element": true, "eliminate": true, "elite": true,
		"else": true, "elsewhere": true, "email": true, "embarrass": true,
		"emerge": true, "emergency": true, "emission": true, "emotion": true,
		"emotional": true, "emphasis": true, "emphasize": true, "empire": true,
		"employ": true, "employee": true, "employer": true, "employment": true,
		"empty": true, "enable": true, "encounter": true, "encourage": true,
		"end": true, "enemy": true, "energy": true, "enforce": true,
		"engage": true, "engine": true, "engineer": true, "engineering": true,
		"english": true, "enhance": true, "enjoy": true, "enormous": true,
		"enough": true, "ensure": true, "enter": true, "enterprise": true,
		"entertainment": true, "entire": true, "entirely": true, "entrance": true,
		"entry": true, "environment": true, "environmental": true, "episode": true,
		"equal": true, "equally": true, "equipment": true, "era": true,
		"error": true, "escape": true, "especially": true, "essay": true,
		"essential": true, "essentially": true, "establish": true, "establishment": true,
		"estate": true, "estimate": true, "etc": true, "ethnic": true,
		"europe": true, "european": true, "evaluate": true, "evaluation": true,
		"even": true, "evening": true, "event": true, "eventually": true,
		"ever": true, "every": true, "everybody": true, "everyday": true,
		"everyone": true, "everything": true, "everywhere": true, "evidence": true,
		"evil": true, "evolution": true, "exact": true, "exactly": true,
		"exam": true, "examination": true, "examine": true, "example": true,
		"exceed": true, "excellent": true, "except": true, "exception": true,
		"exchange": true, "excited": true, "excitement": true, "exciting": true,
		"excuse": true, "executive": true, "exercise": true, "exhibit": true,
		"exhibition": true, "exist": true, "existence": true, "existing": true,
		"exit": true, "expand": true, "expansion": true, "expect": true,
		"expectation": true, "expense": true, "expensive": true, "experience": true,
		"experiment": true, "expert": true, "explain": true, "explanation": true,
		"explore": true, "explosion": true, "export": true, "expose": true,
		"exposure": true, "express": true, "expression": true, "extend": true,
		"extension": true, "extensive": true, "extent": true, "external": true,
		"extra": true, "extraordinary": true, "extreme": true, "extremely": true,
		"eye": true, "face": true, "facebook": true, "facility": true,
		"fact": true, "factor": true, "factory": true, "faculty": true,
		"fail": true, "failure": true, "fair": true, "fairly": true,
		"faith": true, "fake": true, "fall": true, "false": true,
		"fame": true, "familiar": true, "family": true, "famous": true,
		"fan": true, "fancy": true, "fantastic": true, "fantasy": true,
		"far": true, "farm": true, "farmer": true, "fashion": true,
		"fast": true, "fat": true, "father": true, "fault": true,
		"favor": true, "favorite": true, "fear": true, "feature": true,
		"february": true, "federal": true, "fee": true, "feed": true,
		"feedback": true, "feel": true, "feeling": true, "fellow": true,
		"female": true, "fence": true, "festival": true, "few": true,
		"field": true, "fight": true, "fighter": true, "fighting": true,
		"figure": true, "file": true, "fill": true, "film": true,
		"final": true, "finally": true, "finance": true, "financial": true,
		"find": true, "finding": true, "fine": true, "finger": true,
		"finish": true, "fire": true, "firm": true, "first": true,
		"fish": true, "fishing": true, "fit": true, "fitness": true,
		"fix": true, "flag": true, "flame": true, "flash": true,
		"flat": true, "flavor": true, "flee": true, "flesh": true,
		"flexibility": true, "flexible": true, "flight": true, "flip": true,
		"float": true, "floor": true, "flow": true, "flower": true,
		"fly": true, "focus": true, "fold": true, "folk": true,
		"follow": true, "following": true, "food": true, "foot": true,
		"football": true, "for": true, "force": true, "forecast": true,
		"foreign": true, "forest": true, "forever": true, "forget": true,
		"forgive": true, "form": true, "formal": true, "format": true,
		"formation": true, "former": true, "formerly": true, "formula": true,
		"forth": true, "fortune": true, "forward": true, "found": true,
		"foundation": true, "founder": true, "four": true, "frame": true,
		"framework": true, "france": true, "franchise": true, "frank": true,
		"frankly": true, "fraud": true, "free": true, "freedom": true,
		"frequency": true, "frequent": true, "frequently": true, "fresh": true,
		"friday": true, "friend": true, "friendly": true, "friendship": true,
		"from": true, "front": true, "fruit": true, "frustrate": true,
		"frustration": true, "fuel": true, "full": true, "fully": true,
		"fun": true, "function": true, "fund": true, "fundamental": true,
		"funding": true, "funeral": true, "funny": true, "furniture": true,
		"furthermore": true, "future": true, "gain": true, "gallery": true,
		"game": true, "gang": true, "gap": true, "garage": true,
		"garden": true, "gas": true, "gate": true, "gather": true,
		"gay": true, "gear": true, "gender": true, "gene": true,
		"general": true, "generally": true, "generate": true, "generation": true,
		"genetic": true, "gentleman": true, "genuine": true, "geography": true,
		"german": true, "germany": true, "get": true, "giant": true,
		"gift": true, "girl": true, "girlfriend": true, "give": true,
		"given": true, "glad": true, "glance": true, "glass": true,
		"global": true, "glory": true, "goal": true, "god": true,
		"gold": true, "golden": true, "golf": true, "good": true,
		"google": true, "government": true, "governor": true, "grab": true,
		"grace": true, "grade": true, "gradually": true, "graduate": true,
		"grain": true, "grand": true, "grandfather": true, "grandmother": true,
		"grant": true, "graphic": true, "grass": true, "grateful": true,
		"gray": true, "great": true, "greatest": true, "green": true,
		"greet": true, "grey": true, "grid": true, "grocery": true,
		"gross": true, "ground": true, "group": true, "grow": true,
		"growing": true, "growth": true, "guarantee": true, "guard": true,
		"guess": true, "guest": true, "guide": true, "guideline": true,
		"guilty": true, "gun": true, "guy": true, "habit": true,
		"hair": true, "half": true, "hall": true, "hand": true,
		"handle": true, "hang": true, "happen": true, "happiness": true,
		"happy": true, "hard": true, "hardly": true, "hardware": true,
		"harm": true, "hat": true, "hate": true, "have": true,
		"head": true, "headline": true, "headquarters": true, "health": true,
		"healthy": true, "hear": true, "hearing": true, "heart": true,
		"heat": true, "heaven": true, "heavily": true, "heavy": true,
		"height": true, "helicopter": true, "hell": true, "hello": true,
		"help": true, "helpful": true, "her": true, "here": true,
		"heritage": true, "hero": true, "herself": true, "hey": true,
		"hide": true, "high": true, "highlight": true, "highly": true,
		"highway": true, "hill": true, "him": true, "himself": true,
		"hint": true, "hip": true, "hire": true, "his": true,
		"historian": true, "historic": true, "historical": true, "history": true,
		"hit": true, "hockey": true, "hold": true, "holder": true,
		"hole": true, "holiday": true, "holy": true, "home": true,
		"homeless": true, "honest": true, "honestly": true, "honey": true,
		"honor": true, "hook": true, "hope": true, "hopefully": true,
		"horizon": true, "horror": true, "horse": true, "hospital": true,
		"host": true, "hot": true, "hotel": true, "hour": true,
		"house": true, "household": true, "housing": true, "how": true,
		"however": true, "huge": true, "human": true, "humor": true,
		"hundred": true, "hungry": true, "hunt": true, "hunter": true,
		"hunting": true, "hurricane": true, "hurt": true, "husband": true,
		"ice": true, "idea": true, "ideal": true, "identification": true,
		"identify": true, "identity": true, "ignore": true, "ill": true,
		"illegal": true, "illness": true, "illustrate": true, "illustration": true,
		"image": true, "imagination": true, "imagine": true, "immediate": true,
		"immediately": true, "immigrant": true, "immigration": true, "impact": true,
		"implement": true, "implementation": true, "implication": true, "imply": true,
		"import": true, "importance": true, "important": true, "impose": true,
		"impossible": true, "impress": true, "impression": true, "impressive": true,
		"improve": true, "improvement": true, "incident": true, "include": true,
		"including": true, "income": true, "incorporate": true, "increase": true,
		"increasingly": true, "incredible": true, "incredibly": true, "indeed": true,
		"independence": true, "independent": true, "index": true, "india": true,
		"indian": true, "indicate": true, "indication": true, "indicator": true,
		"individual": true, "industrial": true, "industry": true, "infant": true,
		"infection": true, "inflation": true, "influence": true, "inform": true,
		"information": true, "infrastructure": true, "ingredient": true, "initial": true,
		"initially": true, "initiative": true, "injury": true, "inner": true,
		"innocent": true, "innovation": true, "input": true, "inquiry": true,
		"insert": true, "inside": true, "insight": true, "insist": true,
		"inspection": true, "inspector": true, "inspiration": true, "inspire": true,
		"install": true, "installation": true, "instance": true, "instant": true,
		"instead": true, "institute": true, "institution": true, "instruction": true,
		"instructor": true, "instrument": true, "insurance": true, "intellectual": true,
		"intelligence": true, "intelligent": true, "intend": true, "intense": true,
		"intensity": true, "intention": true, "interaction": true, "interest": true,
		"interested": true, "interesting": true, "internal": true, "international": true,
		"internet": true, "interpret": true, "interpretation": true, "intervention": true,
		"interview": true, "into": true, "introduce": true, "introduction": true,
		"invest": true, "investigate": true, "investigation": true, "investigator": true,
		"investment": true, "investor": true, "invitation": true, "invite": true,
		"involve": true, "involved": true, "involvement": true, "iran": true,
		"iraq": true, "iron": true, "island": true, "issue": true,
		"item": true, "itself": true, "jacket": true, "jail": true,
		"james": true, "january": true, "japan": true, "japanese": true,
		"jersey": true, "jesus": true, "jet": true, "jew": true,
		"jewish": true, "job": true, "join": true, "joint": true,
		"joke": true, "journal": true, "journalist": true, "journey": true,
		"joy": true, "judge": true, "judgment": true, "juice": true,
		"july": true, "jump": true, "june": true, "junior": true,
		"jury": true, "just": true, "justice": true, "justify": true,
		"keep": true, "key": true, "kick": true, "kid": true,
		"kill": true, "killer": true, "killing": true, "kind": true,
		"king": true, "kingdom": true, "kiss": true, "kit": true,
		"kitchen": true, "knee": true, "knife": true, "knock": true,
		"know": true, "knowledge": true, "known": true, "lab": true,
		"label": true, "labor": true, "laboratory": true, "lack": true,
		"lady": true, "lake": true, "land": true, "landscape": true,
		"language": true, "lap": true, "laptop": true, "large": true,
		"largely": true, "last": true, "late": true, "later": true,
		"latest": true, "latin": true, "latter": true, "laugh": true,
		"launch": true, "law": true, "lawn": true, "lawsuit": true,
		"lawyer": true, "lay": true, "layer": true, "lead": true,
		"leader": true, "leadership": true, "leading": true, "leaf": true,
		"league": true, "lean": true, "learn": true, "learning": true,
		"least": true, "leather": true, "leave": true, "lecture": true,
		"left": true, "leg": true, "legacy": true, "legal": true,
		"legend": true, "legislation": true, "legitimate": true, "lemon": true,
		"lend": true, "length": true, "less": true, "lesson": true,
		"let": true, "letter": true, "level": true, "liberal": true,
		"liberty": true, "library": true, "license": true, "lie": true,
		"life": true, "lifestyle": true, "lifetime": true, "lift": true,
		"light": true, "like": true, "likely": true, "limit": true,
		"limitation": true, "limited": true, "line": true, "link": true,
		"lion": true, "lip": true, "list": true, "listen": true,
		"literally": true, "literary": true, "literature": true, "little": true,
		"live": true, "living": true, "load": true, "loan": true,
		"lobby": true, "local": true, "locate": true, "location": true,
		"lock": true, "log": true, "logic": true, "london": true,
		"lonely": true, "long": true, "look": true, "loop": true,
		"loose": true, "lord": true, "lose": true, "loss": true,
		"lost": true, "lot": true, "lots": true, "loud": true,
		"love": true, "lovely": true, "lover": true, "low": true,
		"lower": true, "luck": true, "lucky": true, "lunch": true,
		"lung": true, "machine": true, "mad": true, "magazine": true,
		"magic": true, "mail": true, "main": true, "mainly": true,
		"mainstream": true, "maintain": true, "maintenance": true, "major": true,
		"majority": true, "make": true, "maker": true, "makeup": true,
		"male": true, "mall": true, "man": true, "manage": true,
		"management": true, "manager": true, "manner": true, "manufacturer": true,
		"manufacturing": true, "many": true, "map": true, "march": true,
		"margin": true, "mark": true, "market": true, "marketing": true,
		"marketplace": true, "marriage": true, "married": true, "marry": true,
		"mask": true, "mass": true, "massive": true, "master": true,
		"match": true, "mate": true, "material": true, "math": true,
		"matter": true, "maximum": true, "may": true, "maybe": true,
		"mayor": true, "meal": true, "mean": true, "meaning": true,
		"meaningful": true, "meanwhile": true, "measure": true, "measurement": true,
		"meat": true, "mechanism": true, "medal": true, "media": true,
		"medical": true, "medication": true, "medicine": true, "medium": true,
		"meet": true, "meeting": true, "member": true, "membership": true,
		"memory": true, "mental": true, "mention": true, "menu": true,
		"merchant": true, "mercy": true, "mere": true, "merely": true,
		"merge": true, "mess": true, "message": true, "metal": true,
		"method": true, "metro": true, "mexico": true, "middle": true,
		"midnight": true, "might": true, "migration": true, "mild": true,
		"mile": true, "military": true, "milk": true, "million": true,
		"mind": true, "mine": true, "minimum": true, "minister": true,
		"ministry": true, "minor": true, "minority": true, "minute": true,
		"miracle": true, "mirror": true, "miss": true, "missile": true,
		"missing": true, "mission": true, "mistake": true, "mix": true,
		"mixture": true, "mobile": true, "mode": true, "model": true,
		"moderate": true, "modern": true, "modify": true, "mom": true,
		"moment": true, "momentum": true, "money": true, "monitor": true,
		"month": true, "monthly": true, "mood": true, "moon": true,
		"moral": true, "more": true, "moreover": true, "morning": true,
		"mortgage": true, "most": true, "mostly": true, "mother": true,
		"motion": true, "motivation": true, "motor": true, "mount": true,
		"mountain": true, "mouse": true, "mouth": true, "move": true,
		"movement": true, "movie": true, "much": true, "multiple": true,
		"murder": true, "muscle": true, "museum": true, "music": true,
		"musical": true, "muslim": true, "must": true, "mutual": true,
		"mystery": true, "myth": true, "nail": true, "name": true,
		"narrative": true, "narrow": true, "nation": true, "national": true,
		"native": true, "natural": true, "naturally": true, "nature": true,
		"near": true, "nearby": true, "nearly": true, "necessarily": true,
		"necessary": true, "neck": true, "need": true, "negative": true,
		"negotiate": true, "negotiation": true, "neighbor": true, "neighborhood": true,
		"neither": true, "nerve": true, "nervous": true, "net": true,
		"network": true, "never": true, "nevertheless": true, "new": true,
		"newly": true, "news": true, "newspaper": true, "next": true,
		"nice": true, "night": true, "nine": true, "nobody": true,
		"nod": true, "noise": true, "none": true, "nonetheless": true,
		"nor": true, "normal": true, "normally": true, "north": true,
		"northern": true, "nose": true, "not": true, "note": true,
		"nothing": true, "notice": true, "notion": true, "novel": true,
		"november": true, "now": true, "nowhere": true, "nuclear": true,
		"number": true, "numerous": true, "nurse": true, "nursing": true,
		"object": true, "objective": true, "obligation": true, "observation": true,
		"observe": true, "observer": true, "obtain": true, "obvious": true,
		"obviously": true, "occasion": true, "occasionally": true, "occupation": true,
		"occupy": true, "occur": true, "ocean": true, "october": true,
		"odd": true, "odds": true, "off": true, "offense": true,
		"offensive": true, "offer": true, "office": true, "officer": true,
		"official": true, "officially": true, "often": true, "oil": true,
		"okay": true, "old": true, "olympic": true, "once": true,
		"one": true, "ongoing": true, "online": true, "only": true,
		"onto": true, "open": true, "opening": true, "operate": true,
		"operation": true, "operator": true, "opinion": true, "opponent": true,
		"opportunity": true, "oppose": true, "opposite": true, "opposition": true,
		"option": true, "orange": true, "order": true, "ordinary": true,
		"organic": true, "organization": true, "organize": true, "orientation": true,
		"origin": true, "original": true, "originally": true, "other": true,
		"others": true, "otherwise": true, "ought": true, "our": true,
		"ourselves": true, "out": true, "outcome": true, "outdoor": true,
		"outer": true, "output": true, "outside": true, "outstanding": true,
		"over": true, "overall": true, "overcome": true, "overlook": true,
		"overnight": true, "overseas": true, "overwhelming": true, "own": true,
		"owner": true, "ownership": true, "pace": true, "pack": true,
		"package": true, "page": true, "pain": true, "paint": true,
		"painting": true, "pair": true, "pakistan": true, "palace": true,
		"palestinian": true, "palm": true, "pan": true, "panel": true,
		"panic": true, "paper": true, "parade": true, "paragraph": true,
		"parallel": true, "parent": true, "paris": true, "park": true,
		"parking": true, "parliament": true, "part": true, "participant": true,
		"participate": true, "participation": true, "particular": true, "particularly": true,
		"partly": true, "partner": true, "partnership": true, "party": true,
		"pass": true, "passage": true, "passenger": true, "passing": true,
		"passion": true, "past": true, "patch": true, "path": true,
		"patient": true, "pattern": true, "pause": true, "pay": true,
		"payment": true, "peace": true, "peak": true, "penalty": true,
		"pension": true, "people": true, "pepper": true, "per": true,
		"perceive": true, "percent": true, "percentage": true, "perception": true,
		"perfect": true, "perfectly": true, "perform": true, "performance": true,
		"perhaps": true, "period": true, "permanent": true, "permission": true,
		"permit": true, "person": true, "personal": true, "personality": true,
		"personally": true, "personnel": true, "perspective": true, "persuade": true,
		"pet": true, "phase": true, "phenomenon": true, "philosophy": true,
		"phone": true, "photo": true, "photograph": true, "photographer": true,
		"photography": true, "phrase": true, "physical": true, "physically": true,
		"physician": true, "piano": true, "pick": true, "picture": true,
		"pie": true, "piece": true, "pilot": true, "pin": true,
		"pink": true, "pipe": true, "pitch": true, "place": true,
		"placement": true, "plain": true, "plan": true, "plane": true,
		"planet": true, "planning": true, "plant": true, "plastic": true,
		"plate": true, "platform": true, "play": true, "player": true,
		"playoff": true, "plea": true, "pleasant": true, "please": true,
		"pleasure": true, "plenty": true, "plot": true, "plus": true,
		"pocket": true, "poem": true, "poet": true, "poetry": true,
		"point": true, "pole": true, "police": true, "policy": true,
		"political": true, "politically": true, "politician": true, "politics": true,
		"poll": true, "pollution": true, "pool": true, "poor": true,
		"pop": true, "popular": true, "popularity": true, "population": true,
		"port": true, "portfolio": true, "portion": true, "portrait": true,
		"portray": true, "pose": true, "position": true, "positive": true,
		"possess": true, "possession": true, "possibility": true, "possible": true,
		"possibly": true, "post": true, "pot": true, "potato": true,
		"potential": true, "potentially": true, "pound": true, "pour": true,
		"poverty": true, "powder": true, "power": true, "powerful": true,
		"practical": true, "practice": true, "praise": true, "pray": true,
		"prayer": true, "precisely": true, "predict": true, "prediction": true,
		"prefer": true, "preference": true, "pregnancy": true, "pregnant": true,
		"preliminary": true, "premier": true, "premise": true, "premium": true,
		"preparation": true, "prepare": true, "prescription": true, "presence": true,
		"present": true, "presentation": true, "preserve": true, "president": true,
		"presidential": true, "press": true, "pressure": true, "presumably": true,
		"pretend": true, "pretty": true, "prevent": true, "previous": true,
		"previously": true, "price": true, "pride": true, "primarily": true,
		"primary": true, "prime": true, "prince": true, "princess": true,
		"principal": true, "principle": true, "print": true, "prior": true,
		"priority": true, "prison": true, "prisoner": true, "privacy": true,
		"private": true, "prize": true, "probably": true, "problem": true,
		"procedure": true, "proceed": true, "process": true, "produce": true,
		"producer": true, "product": true, "production": true, "profession": true,
		"professional": true, "professor": true, "profile": true, "profit": true,
		"program": true, "progress": true, "project": true, "prominent": true,
		"promise": true, "promote": true, "promotion": true, "prompt": true,
		"proof": true, "proper": true, "properly": true, "property": true,
		"proportion": true, "proposal": true, "propose": true, "proposed": true,
		"prosecutor": true, "prospect": true, "protect": true, "protection": true,
		"protein": true, "protest": true, "proud": true, "prove": true,
		"provide": true, "provider": true, "province": true, "provision": true,
		"psychological": true, "psychology": true, "public": true, "publication": true,
		"publicly": true, "publish": true, "publisher": true, "pull": true,
		"pump": true, "punch": true, "punishment": true, "pupil": true,
		"purchase": true, "pure": true, "purple": true, "purpose": true,
		"pursue": true, "pursuit": true, "push": true, "put": true,
		"qualify": true, "quality": true, "quarter": true, "quarterback": true,
		"queen": true, "question": true, "quick": true, "quickly": true,
		"quiet": true, "quietly": true, "quit": true, "quite": true,
		"quote": true, "race": true, "racial": true, "racism": true,
		"rack": true, "radar": true, "radical": true, "radio": true,
		"rage": true, "raid": true, "rail": true, "railroad": true,
		"rain": true, "raise": true, "range": true, "rank": true,
		"ranking": true, "rapid": true, "rapidly": true, "rare": true,
		"rarely": true, "rate": true, "rather": true, "rating": true,
		"ratio": true, "raw": true, "reach": true, "react": true,
		"reaction": true, "read": true, "reader": true, "reading": true,
		"ready": true, "real": true, "realistic": true, "reality": true,
		"realize": true, "really": true, "realm": true, "rear": true,
		"reason": true, "reasonable": true, "recall": true, "receive": true,
		"recent": true, "recently": true, "recipe": true, "recognition": true,
		"recognize": true, "recommend": true, "recommendation": true, "record": true,
		"recording": true, "recover": true, "recovery": true, "recruit": true,
		"red": true, "reduce": true, "reduction": true, "refer": true,
		"reference": true, "reflect": true, "reflection": true, "reform": true,
		"refugee": true, "refuse": true, "regard": true, "regarding": true,
		"regardless": true, "regime": true, "region": true, "regional": true,
		"register": true, "regular": true, "regularly": true, "regulation": true,
		"reinforce": true, "reject": true, "relate": true, "related": true,
		"relation": true, "relationship": true, "relative": true, "relatively": true,
		"relax": true, "release": true, "relevant": true, "relief": true,
		"relieve": true, "religion": true, "religious": true, "rely": true,
		"remain": true, "remaining": true, "remarkable": true, "remember": true,
		"remind": true, "remote": true, "remove": true, "rent": true,
		"repair": true, "repeat": true, "replace": true, "replacement": true,
		"reply": true, "report": true, "reporter": true, "represent": true,
		"representation": true, "representative": true, "republic": true, "republican": true,
		"reputation": true, "request": true, "require": true, "requirement": true,
		"rescue": true, "research": true, "researcher": true, "reservation": true,
		"reserve": true, "resident": true, "residential": true, "resign": true,
		"resist": true, "resistance": true, "resolution": true, "resolve": true,
		"resort": true, "resource": true, "respect": true, "respond": true,
		"respondent": true, "response": true, "responsibility": true, "responsible": true,
		"rest": true, "restaurant": true, "restore": true, "restriction": true,
		"result": true, "retain": true, "retire": true, "retirement": true,
		"retreat": true, "return": true, "reveal": true, "revenue": true,
		"review": true, "revolution": true, "reward": true, "rhythm": true,
		"rice": true, "rich": true, "rid": true, "ride": true,
		"rider": true, "ridge": true, "ridiculous": true, "rifle": true,
		"right": true, "ring": true, "riot": true, "rise": true,
		"rising": true, "risk": true, "rival": true, "river": true,
		"road": true, "rock": true, "rocket": true, "role": true,
		"roll": true, "romantic": true, "roof": true, "room": true,
		"root": true, "rope": true, "rose": true, "rough": true,
		"roughly": true, "round": true, "route": true, "routine": true,
		"row": true, "royal": true, "rub": true, "rubber": true,
		"ruin": true, "rule": true, "ruling": true, "run": true,
		"running": true, "rural": true, "rush": true, "russia": true,
		"russian": true, "sacred": true, "sacrifice": true, "sad": true,
		"safe": true, "safety": true, "sake": true, "salad": true,
		"salary": true, "sale": true, "sales": true, "salt": true,
		"same": true, "sample": true, "sanction": true, "sand": true,
		"satellite": true, "satisfaction": true, "satisfy": true, "saturday": true,
		"sauce": true, "save": true, "saving": true, "say": true,
		"scale": true, "scandal": true, "scared": true, "scenario": true,
		"scene": true, "schedule": true, "scheme": true, "scholar": true,
		"scholarship": true, "school": true, "science": true, "scientific": true,
		"scientist": true, "scope": true, "score": true, "scratch": true,
		"scream": true, "screen": true, "script": true, "sea": true,
		"search": true, "season": true, "seat": true, "second": true,
		"secondary": true, "secret": true, "secretary": true, "section": true,
		"sector": true, "secure": true, "security": true, "see": true,
		"seed": true, "seek": true, "seem": true, "segment": true,
		"seize": true, "select": true, "selection": true, "self": true,
		"sell": true, "senate": true, "senator": true, "send": true,
		"senior": true, "sense": true, "sensitive": true, "sentence": true,
		"separate": true, "separately": true, "september": true, "sequence": true,
		"series": true, "serious": true, "seriously": true, "servant": true,
		"serve": true, "server": true, "service": true, "session": true,
		"set": true, "setting": true, "settle": true, "settlement": true,
		"seven": true, "several": true, "severe": true, "sex": true,
		"sexual": true, "shade": true, "shadow": true, "shake": true,
		"shall": true, "shame": true, "shape": true, "share": true,
		"shareholder": true, "sharp": true, "she": true, "sheet": true,
		"shelf": true, "shell": true, "shelter": true, "shift": true,
		"shine": true, "ship": true, "shipping": true, "shirt": true,
		"shock": true, "shoe": true, "shoot": true, "shooting": true,
		"shop": true, "shopping": true, "shore": true, "short": true,
		"shortly": true, "shot": true, "should": true, "shoulder": true,
		"shout": true, "show": true, "shower": true, "shut": true,
		"sick": true, "side": true, "sign": true, "signal": true,
		"signature": true, "significance": true, "significant": true, "significantly": true,
		"silence": true, "silent": true, "silver": true, "similar": true,
		"similarly": true, "simple": true, "simply": true, "sin": true,
		"since": true, "sing": true, "singer": true, "single": true,
		"sink": true, "sir": true, "sister": true, "sit": true,
		"site": true, "situation": true, "six": true, "size": true,
		"ski": true, "skill": true, "skin": true, "sky": true,
		"slave": true, "sleep": true, "slice": true, "slide": true,
		"slight": true, "slightly": true, "slip": true, "slow": true,
		"slowly": true, "small": true, "smart": true, "smell": true,
		"smile": true, "smoke": true, "smooth": true, "snap": true,
		"snow": true, "social": true, "society": true, "soft": true,
		"software": true, "soil": true, "solar": true, "soldier": true,
		"solid": true, "solution": true, "solve": true, "some": true,
		"somebody": true, "somehow": true, "someone": true, "something": true,
		"sometimes": true, "somewhat": true, "somewhere": true, "son": true,
		"song": true, "soon": true, "sophisticated": true, "sorry": true,
		"sort": true, "soul": true, "sound": true, "source": true,
		"south": true, "southern": true, "space": true, "spanish": true,
		"speak": true, "speaker": true, "special": true, "specialist": true,
		"species": true, "specific": true, "specifically": true, "spectrum": true,
		"speculation": true, "speech": true, "speed": true, "spell": true,
		"spend": true, "spending": true, "spin": true, "spirit": true,
		"spiritual": true, "split": true, "spokesman": true, "sponsor": true,
		"sport": true, "sports": true, "spot": true, "spread": true,
		"spring": true, "squad": true, "square": true, "squeeze": true,
		"stability": true, "stable": true, "stadium": true, "staff": true,
		"stage": true, "stair": true, "stake": true, "stand": true,
		"standard": true, "standing": true, "star": true, "stare": true,
		"start": true, "state": true, "statement": true, "station": true,
		"statistics": true, "status": true, "stay": true, "steady": true,
		"steal": true, "steel": true, "steep": true, "stem": true,
		"step": true, "stick": true, "still": true, "stimulus": true,
		"stock": true, "stomach": true, "stone": true, "stop": true,
		"storage": true, "store": true, "storm": true, "story": true,
		"straight": true, "strange": true, "stranger": true, "strategic": true,
		"strategy": true, "stream": true, "street": true, "strength": true,
		"strengthen": true, "stress": true, "stretch": true, "strict": true,
		"strike": true, "string": true, "strip": true, "stroke": true,
		"strong": true, "strongly": true, "structure": true, "struggle": true,
		"student": true, "studio": true, "study": true, "stuff": true,
		"stupid": true, "style": true, "subject": true, "submit": true,
		"subsequent": true, "substance": true, "substantial": true, "succeed": true,
		"success": true, "successful": true, "successfully": true, "such": true,
		"sudden": true, "suddenly": true, "sue": true, "suffer": true,
		"sufficient": true, "sugar": true, "suggest": true, "suggestion": true,
		"suicide": true, "suit": true, "summer": true, "summit": true,
		"sun": true, "sunday": true, "super": true, "supply": true,
		"support": true, "supporter": true, "suppose": true, "supposed": true,
		"supreme": true, "sure": true, "surely": true, "surface": true,
		"surgery": true, "surprise": true, "surprised": true, "surprising": true,
		"surround": true, "survey": true, "survival": true, "survive": true,
		"survivor": true, "suspect": true, "suspend": true, "sustain": true,
		"swear": true, "sweep": true, "sweet": true, "swim": true,
		"swimming": true, "swing": true, "switch": true, "symbol": true,
		"symptom": true, "system": true, "table": true, "tabloid": true,
		"tactic": true, "tail": true, "take": true, "tale": true,
		"talent": true, "talented": true, "talk": true, "tall": true,
		"tank": true, "tap": true, "tape": true, "target": true,
		"task": true, "taste": true, "tax": true, "tea": true,
		"teach": true, "teacher": true, "teaching": true, "team": true,
		"tear": true, "tech": true, "technical": true, "technique": true,
		"technology": true, "teen": true, "teenager": true, "telephone": true,
		"television": true, "tell": true, "temperature": true, "temple": true,
		"temporary": true, "ten": true, "tend": true, "tendency": true,
		"tennis": true, "tension": true, "tent": true, "term": true,
		"terms": true, "terrible": true, "territory": true, "terror": true,
		"terrorism": true, "terrorist": true, "test": true, "testify": true,
		"testimony": true, "testing": true, "text": true, "than": true,
		"thank": true, "thanks": true, "that": true, "theater": true,
		"their": true, "them": true, "theme": true, "themselves": true,
		"then": true, "theory": true, "therapy": true, "there": true,
		"therefore": true, "thick": true, "thin": true, "thing": true,
		"think": true, "thinking": true, "third": true, "thirty": true,
		"this": true, "thorough": true, "those": true, "though": true,
		"thought": true, "thousand": true, "threat": true, "threaten": true,
		"three": true, "throat": true, "through": true, "throughout": true,
		"throw": true, "thus": true, "ticket": true, "tie": true,
		"tight": true, "time": true, "timeline": true, "tiny": true,
		"tip": true, "tire": true, "tired": true, "tissue": true,
		"title": true, "tobacco": true, "today": true, "together": true,
		"tomato": true, "tomorrow": true, "tone": true, "tongue": true,
		"tonight": true, "too": true, "tool": true, "tooth": true,
		"top": true, "topic": true, "total": true, "totally": true,
		"touch": true, "tough": true, "tour": true, "tournament": true,
		"toward": true, "towards": true, "tower": true, "town": true,
		"track": true, "trade": true, "tradition": true, "traditional": true,
		"traffic": true, "tragedy": true, "trail": true, "train": true,
		"trainer": true, "training": true, "transaction": true, "transfer": true,
		"transform": true, "transformation": true, "transition": true, "translate": true,
		"translation": true, "transportation": true, "trap": true, "travel": true,
		"treat": true, "treatment": true, "treaty": true, "tree": true,
		"tremendous": true, "trend": true, "trial": true, "tribe": true,
		"trick": true, "trigger": true, "trim": true, "trip": true,
		"troop": true, "tropical": true, "trouble": true, "truck": true,
		"true": true, "truly": true, "trust": true, "truth": true,
		"try": true, "tube": true, "tuesday": true, "tune": true,
		"tunnel": true, "turkey": true, "turn": true, "twelve": true,
		"twenty": true, "twice": true, "twin": true, "twist": true,
		"two": true, "type": true, "typical": true, "typically": true,
		"ugly": true, "ultimate": true, "ultimately": true, "unable": true,
		"uncle": true, "under": true, "undergo": true, "understand": true,
		"understanding": true, "unfortunately": true, "uniform": true, "union": true,
		"unique": true, "unit": true, "united": true, "unity": true,
		"universal": true, "universe": true, "university": true, "unknown": true,
		"unless": true, "unlike": true, "unlikely": true, "until": true,
		"unusual": true, "upon": true, "upper": true, "upset": true,
		"urban": true, "urge": true, "use": true, "used": true,
		"useful": true, "user": true, "usual": true, "usually": true,
		"utility": true, "vacation": true, "valley": true, "valuable": true,
		"value": true, "van": true, "variety": true, "various": true,
		"vary": true, "vast": true, "vegetable": true, "vehicle": true,
		"venture": true, "venue": true, "verbal": true, "version": true,
		"versus": true, "very": true, "vessel": true, "veteran": true,
		"via": true, "vice": true, "victim": true, "victory": true,
		"video": true, "view": true, "viewer": true, "village": true,
		"violation": true, "violence": true, "violent": true, "virtual": true,
		"virtually": true, "virtue": true, "virus": true, "visible": true,
		"vision": true, "visit": true, "visitor": true, "visual": true,
		"vital": true, "voice": true, "volume": true, "volunteer": true,
		"vote": true, "voter": true, "vulnerable": true, "wage": true,
		"wait": true, "wake": true, "walk": true, "wall": true,
		"want": true, "war": true, "warm": true, "warn": true,
		"warning": true, "wash": true, "waste": true, "watch": true,
		"water": true, "wave": true, "way": true, "weak": true,
		"wealth": true, "wealthy": true, "weapon": true, "wear": true,
		"weather": true, "web": true, "website": true, "wedding": true,
		"wednesday": true, "week": true, "weekend": true, "weekly": true,
		"weigh": true, "weight": true, "weird": true, "welcome": true,
		"welfare": true, "well": true, "west": true, "western": true,
		"wet": true, "what": true, "whatever": true, "wheel": true,
		"when": true, "whenever": true, "where": true, "whereas": true,
		"wherever": true, "whether": true, "which": true, "while": true,
		"whisper": true, "white": true, "who": true, "whoever": true,
		"whole": true, "whom": true, "whose": true, "why": true,
		"wide": true, "widely": true, "widespread": true, "wife": true,
		"wild": true, "will": true, "willing": true, "win": true,
		"wind": true, "window": true, "wine": true, "wing": true,
		"winner": true, "winter": true, "wire": true, "wisdom": true,
		"wise": true, "wish": true, "with": true, "withdraw": true,
		"within": true, "without": true, "witness": true, "woman": true,
		"wonder": true, "wonderful": true, "wood": true, "wooden": true,
		"word": true, "work": true, "worker": true, "working": true,
		"workout": true, "workplace": true, "workshop": true, "world": true,
		"worried": true, "worry": true, "worse": true, "worst": true,
		"worth": true, "would": true, "wound": true, "wrap": true,
		"write": true, "writer": true, "writing": true, "wrong": true,
		"yard": true, "yeah": true, "year": true, "yellow": true,
		"yes": true, "yesterday": true, "yet": true, "yield": true,
		"york": true, "you": true, "young": true, "your": true,
		"yourself": true, "youth": true, "zone": true, "ipl": true,
		"id": true, "ip": true, "tv": true, "dvd": true, "cd": true,
		"fb": true, "ok": true, "pdf": true, "pm": true, "am": true,
		// Additional loanwords found in dataset
		"undercover": true, "atlanta": true, "inter": true, "april": true,
		"authority": true, "appointment": true, "update": true,
		// More loanwords from failure analysis
		"america": true, "ayurvedic": true, "indore": true, "israel": true,
		"istifa": true, "ebay": true, "udaipur": true, "anchor": true,
		"antifungal": true, "antibiotic": true, "antibody": true, "antivirus": true,
		"and": true, "act": true, "actor": true, "accident": true, "access": true,
		"age": true, "agenda": true, "agency": true, "at": true, "atlas": true,
		"atm": true, "advice": true, "advencher": true, "ncr": true, "animated": true,
		"m": true, "aircooled": true, "l": true, "aluminium": true, "sms": true,
		"st": true, "operating": true, "optical": true, "offline": true, "olive": true,
		"concrete": true, "conductor": true, "condom": true, "cambodia": true,
		"kapoor": true, "commander": true, "kareena": true, "kartavya": true,
		// Celebrity/brand names that use English spelling
		"katrina": true, "kaif": true, "hrithik": true, "roshan": true,
		"amitabh": true, "bachchan": true, "shahrukh": true, "priyanka": true,
		"chopra": true, "deepika": true, "padukone": true, "ranveer": true,
		"singh": true, "ranbir": true, "alia": true, "bhatt": true,
		// More technical/modern terms
		"bluetooth": true, "wifi": true, "usb": true, "lcd": true, "led": true,
		"hdmi": true, "gps": true, "sim": true, "otp": true,
		"url": true, "html": true, "css": true, "doc": true,
		"jpg": true, "png": true, "gif": true, "mp3": true, "mp4": true,
		// More common loanwords
		"taxi": true, "jeep": true, "scooter": true,
		"rickshaw": true, "petrol": true, "diesel": true,
		"kilometer": true, "liter": true,
		"kilogram": true, "rupee": true, "paisa": true,
	}

	// Exclude Hindi words that coincidentally match English spellings
	hindiWordsMatchingEnglish := map[string]bool{
		"gun":   true, // गुण = quality/virtue
		"tap":   true, // तप = penance
		"tune":  true, // तूने = you (did)
		"pan":   true, // पान = betel leaf
		"sale":  true, // साले = brother-in-law
		"son":   true, // सोन = name/gold
		"none":  true, // नन = nun (but also Hindi)
		"nine":  true, // नाइन = can be Hindi
		"pet":   true, // पेट = stomach
		"pair":  true, // पैर = foot/leg
		"dixit": true, // दीक्षित = surname
		"wazir": true, // वजीर = minister
	}
	if hindiWordsMatchingEnglish[lower] {
		return false
	}

	if englishWords[lower] {
		return true
	}

	// Patterns that strongly indicate English spelling
	// Only use patterns that are unambiguously English
	englishPatterns := []string{
		// English-only letter combinations
		"qu", "x", "z", "ght", "tch", "dge", "ck",
		// English suffixes
		"tion", "sion",
	}

	for _, p := range englishPatterns {
		if strings.Contains(lower, p) {
			return true
		}
	}

	// "ph" is tricky - it's English in "phone" but Hindi phonetic in "phal"
	// Only count as English if NOT at start (Hindi words like phal, phool start with ph)
	if strings.Contains(lower, "ph") && !strings.HasPrefix(lower, "ph") {
		return true
	}

	return false
}

func main() {
	file, err := os.Open("all_high_conf.tsv")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	nativeFile, err := os.Create("native_hindi.tsv")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating native file: %v\n", err)
		os.Exit(1)
	}
	defer nativeFile.Close()

	loanwordFile, err := os.Create("english_loanwords.tsv")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating loanword file: %v\n", err)
		os.Exit(1)
	}
	defer loanwordFile.Close()

	scanner := bufio.NewScanner(file)
	nativeCount := 0
	loanwordCount := 0

	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Split(line, "\t")
		if len(parts) < 2 {
			continue
		}
		hindi := parts[0]
		expected := parts[1]

		if isEnglishLoanword(hindi, expected) {
			fmt.Fprintln(loanwordFile, line)
			loanwordCount++
		} else {
			fmt.Fprintln(nativeFile, line)
			nativeCount++
		}
	}

	fmt.Printf("Split complete:\n")
	fmt.Printf("  Native Hindi: %d words -> native_hindi.tsv\n", nativeCount)
	fmt.Printf("  English loanwords: %d words -> english_loanwords.tsv\n", loanwordCount)
}
