package hindi

import (
	_ "embed"
	"strings"
	"sync"
)

// High-confidence romanization lexicon: native word -> attested human spelling,
// built from Dakshina TRAIN words whose best spelling has >=4 attestations
// (multiple annotators agreeing = common, confident vocabulary). Generated by
// tools/schwa/build_lexicon.py. This handles loanwords, names, and compounds
// that surface rules cannot (अंकल→uncle, अंग्रेजी→angreji), with the rule engine
// as the fallback for out-of-vocabulary words.
//
// NOTE: this is a production feature, deliberately NOT used in the accuracy
// benchmark (the curated set is drawn from the same TRAIN pool, so scoring with
// the lexicon would be circular). See docs/reviews/2026-09-04-h3-lexicon-layer.md.

//go:embed lexicon.tsv
var lexiconTSV string

var (
	lexiconOnce sync.Once
	lexiconMap  map[string]string
)

func loadLexicon() map[string]string {
	lexiconOnce.Do(func() {
		m := make(map[string]string)
		for _, line := range strings.Split(lexiconTSV, "\n") {
			line = strings.TrimRight(line, "\r")
			if line == "" {
				continue
			}
			tab := strings.IndexByte(line, '\t')
			if tab <= 0 || tab >= len(line)-1 {
				continue
			}
			m[line[:tab]] = line[tab+1:]
		}
		lexiconMap = m
	})
	return lexiconMap
}

// LexiconLookup implements core.LexiconProvider. It returns the attested spelling
// for a known native word, or ("", false) for out-of-vocabulary words.
func (h Hindi) LexiconLookup(word string) (string, bool) {
	roman, ok := loadLexicon()[word]
	return roman, ok
}

// LexiconSize reports the number of entries (useful for coverage reporting/tests).
func LexiconSize() int { return len(loadLexicon()) }
